// <auto-generated />
namespace CourseSelecting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CourseSelectingV18 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CourseSelectingV18));
        
        string IMigrationMetadata.Id
        {
            get { return "201609020121055_CourseSelectingV1.8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
